import crypto from 'node:crypto';
import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { createRelayServer } from '../src/server.js';
function config(){const publicOrigin='https://relay.test';return{host:'127.0.0.1',port:0,publicOrigin,oauthIssuer:publicOrigin,mcpResource:`${publicOrigin}/mcp`,relayTokenSecret:'h'.repeat(48),mcpTimeoutMs:2500,pairTtlMs:5000,pairCredentialTtlMs:365*24*60*60*1000,capabilityTtlMs:10*60*1000,oauthCodeTtlMs:5*60*1000,oauthAccessTtlMs:10*60*1000,oauthRefreshTtlMs:30*24*60*60*1000,maxBodyBytes:1024*1024,pairAttemptWindowMs:10*60*1000,maxPairAttemptsPerIp:8,allowedClientId:'https://chatgpt.test/client-metadata.json',allowedRedirectUris:['https://chatgpt.test/oauth/callback']};}
function stubDeviceRelay(){return{handleUpgrade(_req,socket){socket.destroy();},connectedDeviceCount(){return 0;},pendingPairCount(){return 1;},claimPairing(code){if(code!=='12345678')return null;return{deviceId:'a'.repeat(24),pairId:'pair_generation_1234567890'};},exchangePairCredential(){return null;},verifyCapability(){return null;},presence(){return{deviceId:'a'.repeat(24),connected:false,sessionEpoch:null};},async forwardMcp(){throw new Error('device forwarding not expected in this test');}};}
function challenge(verifier){return crypto.createHash('sha256').update(verifier,'utf8').digest('base64url');}
async function start(t){const cfg=config();const server=createRelayServer(cfg,stubDeviceRelay());server.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>server.close());return{cfg,base:`http://127.0.0.1:${server.address().port}`};}
test('public OAuth metadata is available at both RFC 9728 resource paths',async(t)=>{const{cfg,base}=await start(t);for(const path of['/.well-known/oauth-protected-resource','/.well-known/oauth-protected-resource/mcp']){const response=await fetch(`${base}${path}`);assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'no-store');const body=await response.json();assert.equal(body.resource,cfg.mcpResource);assert.deepEqual(body.authorization_servers,[cfg.oauthIssuer]);}const as=await fetch(`${base}/.well-known/oauth-authorization-server`);assert.equal(as.status,200);const metadata=await as.json();assert.equal(metadata.issuer,cfg.oauthIssuer);assert.deepEqual(metadata.code_challenge_methods_supported,['S256']);assert.deepEqual(metadata.token_endpoint_auth_methods_supported,['none']);});
test('authorization form uses signed request state and token endpoint enforces one-time PKCE exchange',async(t)=>{const{cfg,base}=await start(t);const verifier='pkce-verifier-abcdefghijklmnopqrstuvwxyz-1234567890';const query=new URLSearchParams({response_type:'code',client_id:cfg.allowedClientId,redirect_uri:cfg.allowedRedirectUris[0],resource:cfg.mcpResource,scope:'android.observe android.control',state:'chatgpt-state-123',code_challenge:challenge(verifier),code_challenge_method:'S256'});const authorize=await fetch(`${base}/oauth/authorize?${query}`);assert.equal(authorize.status,200);assert.equal(authorize.headers.get('cache-control'),'no-store');assert.equal(authorize.headers.get('x-frame-options'),'DENY');assert.match(authorize.headers.get('content-security-policy')||'',/frame-ancestors 'none'/);const html=await authorize.text();const requestToken=html.match(/name="request_token" value="([^"]+)"/)?.[1];assert.ok(requestToken);assert.equal(html.includes(cfg.allowedRedirectUris[0]),false);const approval=await fetch(`${base}/oauth/authorize`,{method:'POST',redirect:'manual',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({request_token:requestToken,pairing_code:'12345678'})});assert.equal(approval.status,302);const redirect=new URL(approval.headers.get('location'));assert.equal(`${redirect.origin}${redirect.pathname}`,cfg.allowedRedirectUris[0]);assert.equal(redirect.searchParams.get('state'),'chatgpt-state-123');assert.equal(redirect.searchParams.get('iss'),cfg.oauthIssuer);const code=redirect.searchParams.get('code');assert.ok(code);const tokenBody=new URLSearchParams({grant_type:'authorization_code',code,code_verifier:verifier,client_id:cfg.allowedClientId,redirect_uri:cfg.allowedRedirectUris[0],resource:cfg.mcpResource});const token=await fetch(`${base}/oauth/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:tokenBody});assert.equal(token.status,200);const tokens=await token.json();assert.equal(tokens.token_type,'Bearer');assert.equal(tokens.expires_in,600);assert.ok(tokens.access_token);assert.ok(tokens.refresh_token);const replay=await fetch(`${base}/oauth/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:tokenBody});assert.equal(replay.status,400);assert.equal((await replay.json()).error,'invalid_grant');});
test('public /mcp is mounted and unauthenticated callers receive OAuth discovery challenge',async(t)=>{const{base}=await start(t);const response=await fetch(`${base}/mcp`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'server/discover',params:{}})});assert.equal(response.status,401);assert.match(response.headers.get('www-authenticate')||'',/oauth-protected-resource\/mcp/);});
